const data = {
  products: [
    {
      name: 'free shirt',
      slug: 'free-shirt',
      category: 'Shirt',
      image: '/images/shitrt1.jpg',
      price: 70,
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
      brand: 'Nike',
    },
    {
      name: 'free shirt',
      slug: 'free-shirt',
      category: 'Shirt',
      image: '/images/shitrt1.jpg',
      price: 70,
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
      brand: 'Nike',
    },
    {
      name: 'free shirt',
      slug: 'free-shirt',
      category: 'Shirt',
      image: '/images/shitrt1.jpg',
      price: 70,
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
      brand: 'Nike',
    },
    {
      name: 'free shirt',
      slug: 'free-shirt',
      category: 'Shirt',
      image: '/images/shitrt1.jpg',
      price: 70,
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
      brand: 'Nike',
    },
    {
      name: 'free shirt',
      slug: 'free-shirt',
      category: 'Shirt',
      image: '/images/shitrt1.jpg',
      price: 70,
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
      brand: 'Nike',
    },
    {
      name: 'free shirt',
      slug: 'free-shirt',
      category: 'Shirt',
      image: '/images/shitrt1.jpg',
      price: 70,
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
      brand: 'Nike',
    },
  ],
};

export default data;
