import Head from 'next/head';
import Card from '../components/card';
import Header from '../components/header';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="text-center">
        <h1 className=" text-gray-600 font-bold text-5xl">Hello WOrld</h1>
        <h1 className=" text-sm font-bold">Hello WOrld Movies Top</h1>
      </div>
      <div className="xl:mx-auto lg:container lg:max-auto h-32 mt-10">
        <div className="flex justify-center items-center space-x-3">
          <div className="w-600 h-16 bg-slate-200 drop-shadow-md text-center flex justify-center items-center">
            Hot Movies 2022
          </div>
        </div>
      </div>
      <div className="mt-5 flex flex-wrap">
        <Card></Card>

        <Card></Card>
      </div>
      <footer className="drop-shadow container max-auto h-16 bg-gray-700 text-slate-100">
        hello world @2022
      </footer>
    </div>
  );
}
